### ISSUE TITLE
Do we have a plan to publish the new version of NPM package?

### ISSUE THREAD

**Issue by seanxlliu** [wechaty/wechaty-puppet-puppeteer#110]
I think many our guys are waiting for the fix of sending file

**Comment by huan** [comment]
Yes, we should!

Would you like to send a PR to do this? ;-)

**Comment by seanxlliu** [comment]
I mean we should publish a new npm package to include this fix [PR#106 ](https://github.com/Chatie/wechaty-puppet-puppeteer/pull/106). I don't know how I can publish a NPM package by creating a PR. @huan

**Comment by huan** [comment]
Create a PR to upgrade the version, then the new version will be published after your PR.

**Comment by seanxlliu** [comment]
#111 here we go!

**Comment by suntong** [comment]
Can this one be closed now?

**Comment by huan** [comment]
@suntong Appreciate for the kindly house cleaning noticing!

I have added a Triage ROLE to our @wechaty/contributors so that all the contributors can help the community to manage the Issues because I trust @wechaty/contributors as we are all professional open-source developers.

So please feel free to help the community to manage Issues when you believe it's necessary, from the professional open-source developers perspective.

Thank you very much.

**Comment by suntong** [comment]
Sure. Let me perform my first honorable duty, which is in my best judgement, that this issue can be close. :)
